### ISSUE TITLE
ModuleNotFoundError: No module named 'pysnow.legacy'

### ISSUE THREAD

**Issue by tarkatronic** [rbw0/pysnow#70]
After installing 0.6.0, I am receiving the error:

```python
>>> import pysnow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.6/site-packages/pysnow/__init__.py", line 4, in <module>
    from .client import Client
  File "lib/python3.6/site-packages/pysnow/client.py", line 9, in <module>
    from .legacy.request import LegacyRequest
ModuleNotFoundError: No module named 'pysnow.legacy'
>>>
```

**Comment by rbw0** [comment]
Hello,

This seems to be an issue with the package uploaded to pypi. I'll have it fixed asap.
Thanks for reporting.

/Robert

**Comment by rbw0** [comment]
Fixed. Thanks again for reporting.
